name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up libcurl
        run: sudo apt-get update && sudo apt-get install -y libcurl4-gnutls-dev
        
      - name: Build and run
        run: make
        
      - name: Run tests
        run: make test